#!/bin/sh

# We need to use this fauxbin until the resolution of
# https://github.com/syncthing/syncthing/issues/1056
if [ -f "/data/.stfolder" ]; then
  mv /data/.stfolder /tmp/.stfolder
fi

if [ -f "/data/.stignore" ]; then
  mv /data/.stignore /tmp/.stignore
fi

# We need to do this for SSH add now as well
eval `ssh-agent -s` > /dev/null
ssh-add /ssh/.ssh/id_rsa > /dev/null

git config --global user.name "$GITUSER"
git config --global user.email $GITUSER@kalabox2

git "$@"

# Move this back
if [ -f "/tmp/.stfolder" ]; then
  mv /tmp/.stfolder /data/.stfolder
fi

# Move this back
if [ -f "/tmp/.stignore" ]; then
  mv /tmp/.stignore /data/.stignore
fi
